version: '3.9'

services:
  delta-ecommerce:
    restart: always
    container_name: delta-ecommerce
    build:
      context: ./
      dockerfile: Dockerfile
    # volumes:
    #   - ./runtime:/var/www/html/runtime   # Mount runtime for logs & cache
    #   - ./web:/var/www/html/web           # Mount Yii2 web root
    ports:
      - "97:80"   # Map external port 200 to container's port 80
    networks:
      - shared

networks:
  shared:
    name: shared
    external: true